[package]
name = "popopt"
version = "0.1.0"
edition = "2021"
authors = ["杜 世橋 Du Shiqiao <lucidfrontier.45@gmail.com>"]

[dependencies]
anyhow = "1.0.89"
ndarray = "0.17.1"
ordered-float = "5.1.0"
rand = "0.9.2"
